project-name: Portfolio Website for NZSmartie
base-path: /
markdown:
  extensions:
    markdown.extensions.codehilite:
      css_class: 'highlight'
    markdown.extensions.toc:
      anchorlink: true
